# Generated by Django 3.2.18 on 2023-05-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingproducts',
            name='max_limit',
            field=models.IntegerField(null=True),
        ),
    ]
